kelolaToko/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("auth/", include("authentication.urls")),
]

main/urls.py
from django.urls import path
from main.views import (
    index,
    add_product,
    delete_product,
    add_category,
    delete_category,
    get_product_xml,
    get_product_json,
    get_product_by_id_xml,
    get_category_by_id_json,
    get_category_by_id_xml,
    get_product_by_id_json,
    get_category_json,
    get_category_xml,
    login_user,
    logout_user,
    register,
    sold_product,
    increment_product,
    create_product_ajax,
    create_category_ajax,
    delete_product_ajax,
    delete_category_ajax,
)

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("add-product", add_product, name="add-product"),
    path("delete-product", delete_product, name="delete-product"),
    path("add-category", add_category, name="add-category"),
    path("delete-category", delete_category, name="delete-category"),
    path("get-product/xml", get_product_xml, name="get-product-xml"),
    path("get-product/json", get_product_json, name="get-product-json"),
    path("get-product/xml/<str:id>", get_product_by_id_xml, name="get-product-id-xml"),
    path(
        "get-product/json/<str:id>", get_product_by_id_json, name="get-product-id-json"
    ),
    path("get-category/xml", get_category_xml, name="get-category-xml"),
    path("get-category/json", get_category_json, name="get-category-json"),
    path(
        "get-category/xml/<str:id>", get_category_by_id_xml, name="get-category-id-xml"
    ),
    path(
        "get-category/json/<str:id>",
        get_category_by_id_json,
        name="get-category-id-json",
    ),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("register/", register, name="register"),
    path("sold-product/", sold_product, name="sold-product"),
    path("increment-product/", increment_product, name="increment-product"),
    path("create-product-ajax/", create_product_ajax, name="create-product-ajax"),
    path("create-category-ajax/", create_category_ajax, name="create-category-ajax"),
    path("delete-product-ajax/", delete_product_ajax, name="delete-product-ajax"),
    path("delete-category-ajax/", delete_category_ajax, name="delete-category-ajax"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>kelolaToko</title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'src/styles.css' %}"
    />
    {% comment %} <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.css" rel="stylesheet" /> {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.8.1/flowbite.min.js"></script>

    {% block meta %} {% endblock meta %}
  </head>

  <body class="bg-[#EFF4FF]">
    <nav
      class="z-50 sticky inset-0 flex flex-col bg-white w-full items-center justify-center"
    >
      <div
        class="flex w-full gap-16 px-4 py-3 justify-center"
      >
        <a href={%url 'main:index'%}>
          <h1 class='font-InterBold text-m lg:text-xl'>kelolaToko</h1>
        </a>
      </div>
    </nav>

    <div class='px-2 py-4 lg:px-4'>
        {% block content %} {% endblock content %}
    </div>
   
  </body>
</html>