kelolaToko/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
    path("__reload__/", include("django_browser_reload.urls")),
    path("auth/", include("authentication.urls")),
]

main/urls.py
from django.urls import path
from main.views import (
    index,
    add_product,
    delete_product,
    add_category,
    delete_category,
    get_product_xml,
    get_product_json,
    get_product_by_id_xml,
    get_category_by_id_json,
    get_category_by_id_xml,
    get_product_by_id_json,
    get_category_json,
    get_category_xml,
    login_user,
    logout_user,
    register,
    sold_product,
    increment_product,
    create_product_ajax,
    create_category_ajax,
    delete_product_ajax,
    delete_category_ajax,
)

app_name = "main"

urlpatterns = [
    path("", index, name="index"),
    path("add-product", add_product, name="add-product"),
    path("delete-product", delete_product, name="delete-product"),
    path("add-category", add_category, name="add-category"),
    path("delete-category", delete_category, name="delete-category"),
    path("get-product/xml", get_product_xml, name="get-product-xml"),
    path("get-product/json", get_product_json, name="get-product-json"),
    path("get-product/xml/<str:id>", get_product_by_id_xml, name="get-product-id-xml"),
    path(
        "get-product/json/<str:id>", get_product_by_id_json, name="get-product-id-json"
    ),
    path("get-category/xml", get_category_xml, name="get-category-xml"),
    path("get-category/json", get_category_json, name="get-category-json"),
    path(
        "get-category/xml/<str:id>", get_category_by_id_xml, name="get-category-id-xml"
    ),
    path(
        "get-category/json/<str:id>",
        get_category_by_id_json,
        name="get-category-id-json",
    ),
    path("login/", login_user, name="login"),
    path("logout/", logout_user, name="logout"),
    path("register/", register, name="register"),
    path("sold-product/", sold_product, name="sold-product"),
    path("increment-product/", increment_product, name="increment-product"),
    path("create-product-ajax/", create_product_ajax, name="create-product-ajax"),
    path("create-category-ajax/", create_category_ajax, name="create-category-ajax"),
    path("delete-product-ajax/", delete_product_ajax, name="delete-product-ajax"),
    path("delete-category-ajax/", delete_category_ajax, name="delete-category-ajax"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid


class BaseModel(models.Model):
    objects = models.Manager()

    class Meta:
        abstract = True


class Product(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, blank=False, null=False, unique=False)
    description = models.TextField(blank=True, null=True)
    price = models.IntegerField(blank=False, null=False)
    stock = models.IntegerField(blank=False, null=False)
    sold = models.IntegerField(blank=False, null=False, default=0)
    category = models.ForeignKey(
        "Category", on_delete=models.RESTRICT, blank=True, null=True
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Category(BaseModel):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255, blank=False, null=False, unique=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

main/forms.py
from django.forms import ModelForm, ModelChoiceField, ValidationError
from main.models import Product, Category


class ProductForm(ModelForm):
    category = ModelChoiceField(queryset=Category.objects.none(), to_field_name="name", required=False,
                                empty_label="null")
    
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)

    class Meta:
        model = Product
        fields = ["name", "description", "price", "stock", "category"]


class DeleteProductForm(ModelForm):
    product = ModelChoiceField(queryset=Product.objects.none(), to_field_name="name", required=True, empty_label=None)

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['product'].queryset = Product.objects.filter(user=user)
    
    class Meta:
        model = Product
        fields = ["product"]


class CategoryForm(ModelForm):
    class Meta:
        model = Category
        fields = ["name"]


class DeleteCategoryForm(ModelForm):
    category = ModelChoiceField(queryset=Category.objects.none(), to_field_name="name", required=True, empty_label=None)
    
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user)
    
    def clean_category(self):
        category = self.cleaned_data["category"]
        if Product.objects.filter(category=category).exists():
            raise ValidationError(
                "Masih ada produk yang berada dalam kategori ini, silahkan hapus produk dan caba lagi")
        return category

    class Meta:
        model = Category
        fields = ["category"]

main/views.py
from django.shortcuts import render
from main.models import Product, Category
from main.forms import ProductForm, DeleteProductForm, CategoryForm, DeleteCategoryForm
from django.http import (
    HttpResponseNotFound,
    HttpResponseRedirect,
    HttpResponse,
    JsonResponse,
)
from django.urls import reverse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
import datetime


# Create your views here.
@login_required(login_url="/login/")
def index(request):
    list_all_product = (
        Product.objects.select_related("category")
        .values(
            "id",
            "name",
            "description",
            "price",
            "stock",
            "sold",
            "category__name",
        )
        .filter(user=request.user)
    )
    response = {
        "applicationName": "KelolaToko",
        "nama": request.user.username,
        "class": "PBP-F",
        "productData": {"count": len(list_all_product), "products": list_all_product},
        "last_login": request.COOKIES["last_login"],
    }
    return render(request, "index.html", response)


@login_required(login_url="/login/")
def add_product(request):
    form = ProductForm(request.user, request.POST or None)
    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse("main:index"))
    response = {"form": form}
    return render(request, "add-product.html", response)


@login_required(login_url="/login")
def delete_product(request):
    form = DeleteProductForm(request.user, request.POST or None)
    if form.is_valid() and request.method == "POST":
        product = form.cleaned_data["product"]
        product.delete()
        return HttpResponseRedirect(reverse("main:index"))
    response = {"form": form}
    return render(request, "delete-product.html", response)


@login_required(login_url="/login")
def add_category(request):
    form = CategoryForm(request.POST or None)
    if form.is_valid() and request.method == "POST":
        category = form.save(commit=False)
        category.user = request.user
        category.save()
        return HttpResponseRedirect(reverse("main:index"))
    response = {"form": form}
    return render(request, "add-category.html", response)


@login_required(login_url="/login")
def delete_category(request):
    form = DeleteCategoryForm(request.user, request.POST or None)
    if form.is_valid() and request.method == "POST":
        category = form.cleaned_data["category"]
        category.delete()
        return HttpResponseRedirect(reverse("main:index"))
    response = {"form": form}
    return render(request, "delete-category.html", response)


def get_product_xml(request):
    products = Product.objects.all()
    return HttpResponse(
        serializers.serialize("xml", products),
        content_type="application/xml",
        status=200,
    )


def get_product_json(request):
    list_all_product = (
        Product.objects.select_related("category")
        .values(
            "id",
            "name",
            "description",
            "price",
            "stock",
            "sold",
            "category__name",
        )
        .filter(user=request.user)
    )
    list_all_product = list(list_all_product)
    for product in list_all_product:
        product["id"] = str(product["id"])

    response = {"products": list_all_product, "count": len(list_all_product)}
    return HttpResponse(
        json.dumps(response),
        content_type="application/json",
        status=200,
    )


def get_product_by_id_xml(request, id: str):
    product = Product.objects.filter(id=id)

    return HttpResponse(
        serializers.serialize("xml", product),
        content_type="application/xml",
        status=200,
    )


def get_product_by_id_json(request, id: str):
    product = Product.objects.filter(id=id)
    return HttpResponse(
        serializers.serialize("json", product),
        content_type="application/json",
        status=200,
    )


def get_category_xml(request):
    categories = Category.objects.all()
    return HttpResponse(
        serializers.serialize("xml", categories),
        content_type="application/xml",
        status=200,
    )


@login_required(login_url="/login")
@csrf_exempt
def create_product_ajax(request):
    if request.method == "POST":
        body = json.loads(request.body)
        name = body["name"]
        price = body["price"]
        stock = body["stock"]
        description = body["description"]
        category = body["category"]
        if category != "None":
            Product.objects.create(
                name=name,
                price=price,
                stock=stock,
                description=description,
                category=Category.objects.get(id=category),
                user=request.user,
            )
        else:
            Product.objects.create(
                name=name,
                price=price,
                stock=stock,
                description=description,
                user=request.user,
            )

        return HttpResponse(status=200)
    return HttpResponseNotFound()


@login_required(login_url="/login")
@csrf_exempt
def create_category_ajax(request):
    if request.method == "POST":
        body = json.loads(request.body)
        name = body["name"]
        Category.objects.create(name=name, user=request.user)
        return HttpResponse(status=200)
    return HttpResponseNotFound()


@login_required(login_url="/login")
@csrf_exempt
def delete_product_ajax(request):
    if request.method == "POST":
        body = json.loads(request.body)
        id = body["id"]
        Product.objects.filter(id=id).delete()
        return HttpResponse(status=200)
    return HttpResponseNotFound()


@login_required(login_url="/login")
@csrf_exempt
def delete_category_ajax(request):
    if request.method == "POST":
        body = json.loads(request.body)
        id = body["id"]

        products = Product.objects.filter(category=id)
        if len(products) > 0:
            return HttpResponse(status=401)
        Category.objects.filter(id=id).delete()
        return HttpResponse(status=200)
    return HttpResponseNotFound()


def get_category_json(request):
    categories = Category.objects.values("id", "name").filter(user=request.user)
    categories = list(categories)
    for category in categories:
        category["id"] = str(category["id"])

    response = {"categories": categories, "count": len(categories)}
    return JsonResponse(response)


def get_category_by_id_xml(request, id: str):
    category = Category.objects.filter(id=id)
    return HttpResponse(
        serializers.serialize("xml", category),
        content_type="application/xml",
        status=200,
    )


def get_category_by_id_json(request, id: str):
    category = Category.objects.filter(id=id)
    return HttpResponse(
        serializers.serialize("json", category),
        content_type="application/json",
        status=200,
    )


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")
            return redirect("main:login")
    response = {"form": form}
    return render(request, "register.html", response)


def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:index"))
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, "Sorry, incorrect username or password. Please try again."
            )

    response = {}
    return render(request, "login.html", response)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("main:login"))
    response.delete_cookie("last_login")
    return response


@login_required(login_url="/login")
def sold_product(request):
    if request.method == "POST":
        product_id = request.POST.get("product_id")
        product = Product.objects.get(id=product_id)
        if product.stock > 0:
            product.stock -= 1
            product.sold += 1
        product.save()
        return HttpResponseRedirect(reverse("main:index"))
    return HttpResponseRedirect(reverse("main:index"))


@login_required(login_url="/login")
def increment_product(request):
    if request.method == "POST":
        product_id = request.POST.get("product_id")
        product = Product.objects.get(id=product_id)
        product.stock += 1
        product.save()
        return HttpResponseRedirect(reverse("main:index"))
    return HttpResponseRedirect(reverse("main:index"))

main/templates/add-category.html
{% extends "base.html" %} {% block content %}
<h1 class="font-InterBold text-[28px]">Tambah Kategori</h1>
<form method="POST">
  {% csrf_token %}
  <div class="flex flex-col gap-4 font-Inter w-[400px] px-4">{{ form }}</div>

  <input
    type="submit"
    value="Tambah Kategori"
    class="p-2 rounded-[10px] text-[12px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4 w-36"
  />
</form>

{% endblock content %}

main/templates/add-product.html
{% extends "base.html" %} {% block content %}
<h1 class="font-InterBold text-[28px]">Tambah Produk</h1>
<form method="POST">
  {% csrf_token %}

  <div class="flex flex-col gap-4 font-Inter w-[400px] px-4">{{ form }}</div>
  <input
    type="submit"
    value="Tambah Produk"
    class="p-2 rounded-[10px] text-[14px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4 w-36"
  />
</form>

{% endblock content %}

main/templates/delete-category.html
{% extends "base.html" %} {% block content %}
<h1 class="font-InterBold text-[28px]">Hapus Kategori</h1>
<form method="POST">
  {% csrf_token %}
  <div class="flex flex-col gap-4 font-Inter w-[400px] px-4">{{ form }}</div>

  <input
    type="submit"
    value="Delete Kategori"
    class="p-2 rounded-[10px] text-[12px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4 w-36"
  />
</form>

{% endblock content %}

main/templates/delete-product.html
{% extends "base.html" %} {% block content %}
<h1 class="font-InterBold text-[28px]">Hapus Produk</h1>
<form method="POST">
  {% csrf_token %}
  <div class="flex flex-col gap-4 font-Inter w-[400px] px-4">{{ form }}</div>

  <input
    type="submit"
    value="Delete produk"
    class="p-2 rounded-[10px] text-[12px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4 w-36"
  />
</form>

{% endblock content %}

main/templates/login.html
{% extends 'base.html' %} {% block meta %}
<title>Login</title>
{% endblock meta %} {% block content %}

<div class="relative py-4 w-full flex justify-center items-center">
  <div class="relative flex flex-col items-center top-20">
    <h1 class="flex font-InterBold text-4xl text-center">Welcome Back</h1>

    <form method="POST" action="{%url 'main:login'%}">
      {% csrf_token %}

      <div class="flex flex-col gap-4 w-[250px] mt-10">
        <input
          class="text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc] transition-all"
          placeholder="Username"
          name="username"
        />

        <input
          class="text-[16px] rounded-[10px] px-2 py-1 border-[rgba(168, 168, 168, 0.5)] border-[1px] hover:border-[#727bfc]"
          placeholder="Password"
          name="password"
          type="password"
        />

        <button
          type="submit"
          class="p-2 rounded-[10px] text-[16px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4"
          >
          Login
        </button>
    </form>

  
    <a
      type="submit"
      class="p-2 rounded-[10px] text-[16px] bg-[#3d3e50] text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold"
      href="{% url 'main:register' %}"
    >
      Don't have an account?
    </a>

    <div class='flex flex-col gap-4'>
      {% if messages %}
      <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
      </ul>
      {% endif %}

    </div>
    </div>

  </div>
</div>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %} {% block meta %}
<title>Register</title>
{% endblock meta %} {% block content %}

<div class="login">
  <h1 class="font-InterBold text-[28px]">Register</h1>

  <form method="POST">
    {% csrf_token %}

    <div class="flex flex-col gap-4 font-Inter w-[400px] px-4">{{ form }}</div>

    <input
      type="submit"
      name="submit"
      value="Daftar"
      class="p-2 rounded-[10px] text-[12px] bg-purple-600 text-white bg-gradiend hover:bg-[#727bfc] transition-all text-center font-InterBold mt-4 w-36"
    />
  </form>

  {% if messages %}
  <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
</div>

{% endblock content %}